Restore URC string when using generic URC callback
FreeRTOS/FreeRTOS-Cellular-Interface pull request #86
Opened 2022-04-27 09:01 UTC by ActoryOu

- Restore URC string for generic URC callback for users to differentiate URC token.
- Add an unit-test case to test URC with colon but the token is not in the table.

2022-04-27 12:44 UTC, chinglee-iot approved these changes

2022-04-27 19:33 UTC, paulbartell commented on test/unit-test/cellular_pkthandler_utest.c
> +    _Cellular_GenericCallback_Ignore();
This test should verify that _Cellular_GenericCallback is called with a copy of the input at command.

```suggestion
    _Cellular_GenericCallback_Stub( vVerifyStringContents  );
```

2022-04-27 19:42 UTC, paulbartell requested changes
Only the return value of the call to _Cellular_HandlePacket is checked in the modified test case, so even the previous version of cellular_pkthandler.c would pass the updated test case.

While this updated test case might achieve line / decision coverage, it does not validate whether or not `_Cellular_ProcessGenericUrc` is called.

This test case should also validate that:
1. The callback is actually called
2. That the string returned matches the expected string.

For other cases where a call to `_Cellular_ProcessGenericUrc` is not expected, the test case should assert that `_Cellular_ProcessGenericUrc` was not called.

It may also be helpful to enable the unity memory extension to track calls to malloc/free or enable the gcc -fsanitize=leak option.

2022-04-28 20:50 UTC, paulbartell commented on test/unit-test/cellular_pkthandler_utest.c
> +    Cellular_ATStrDup_StubWithCallback( _CMOCK_Cellular_ATStrDup_CALLBACK );
This stub should be used in the other cases that test URC handling.

2022-04-28 23:51 UTC, paulbartell commented on test/unit-test/cellular_pkthandler_utest.c
> +    Cellular_ATStrDup_StubWithCallback( _CMOCK_Cellular_ATStrDup_CALLBACK );
In other words, anywhere that currently has _Cellular_GenericCallback_Ignore, should instead set the same Cellular_ATStrDup_StubWithCallback callback and verify the result.

2022-04-29 11:07 UTC, chinglee-iot commented
@paulbartell 
Thanks for your feedback.
I also review current test cases for URC handling.

This PR fix the following scenario
* _Cellular_HandlePacket( &context, AT_UNSOLICITED, CELLULAR_AT_MULTI_DATA_WO_PREFIX_STRING_RESP );
  * Input URC is "+QIRD: 32\r123243154354364576587utrhfgdghfg". 
  * Generic URC handler should be called. This PR restore the input string to generic URC handler. The input string passed to generic handler before this PR is "32\r123243154354364576587utrhfgdghfg" and after this PR is "+QIRD: 32\r123243154354364576587utrhfgdghfg". This input string is also compared in _CMOCK_Cellular_Generic_CALLBACK.

The followings are existing test cases related to URC handler
**Invalid parameter test**
* _Cellular_HandlePacket( &context, AT_UNSOLICITED, NULL );
  * CELLULAR_PKT_STATUS_BAD_PARAM should be returned if token string is NULL
* _Cellular_HandlePacket( &context, AT_UNSOLICITED, CELLULAR_PLUS_TOKEN_ONLY_STRING );
  * CELLULAR_PKT_STATUS_BAD_REQUEST should be returned if token string is "+"
* _Cellular_HandlePacket( &context, AT_UNSOLICITED, CELLULAR_SAMPLE_PREFIX_STRING_LARGE_INPUT );
  * CELLULAR_PKT_STATUS_FAILURE should be returned if token string is longer than CELLULAR_AT_MAX_STRING_SIZE
* _Cellular_HandlePacket( &context, AT_UNSOLICITED, CELLULAR_URC_TOKEN_STRING_INPUT );
  *  CELLULAR_PKT_STATUS_FAILURE should be returned if the token string handler function is NULL

**URC token table test**
* _Cellular_HandlePacket( &context, AT_UNSOLICITED, CELLULAR_URC_TOKEN_STRING_INPUT_START_PLUS ); **Updated**
  * Happy path test. The URC token is handled in URC token table. Only token after ":" should be returned. The token is compared. In this case, the passed token is zero length string.

**Generic URC handler test**
* _Cellular_HandlePacket( &context, AT_UNSOLICITED, CELLULAR_URC_TOKEN_STRING_GREATER_INPUT ); **Updated**
  * "RDY" is registered in URC handler table. Input URC is "RDYY". Generic URC handler should be called. "RDYY" is also compared in generic URC handler.
* _Cellular_HandlePacket( &context, AT_UNSOLICITED, CELLULAR_URC_TOKEN_STRING_SMALLER_INPUT ); **Updated**
  * "RDY" is registered in URC handler table. Input URC is "RD". Generic URC handler should be called. "RD" is also compared in generic URC handler.

If more test cases are required, please also share your suggestion to us.

2022-05-03 23:03 UTC, paulbartell commented on test/unit-test/cellular_pkthandler_utest.c
> +static bool passCompareString = false;
passCompareString should be set to 0 in the setUp() function.

2022-05-03 23:07 UTC, paulbartell commented on test/unit-test/cellular_pkthandler_utest.c
> +static bool passCompareString = false;
Nevermind. I see that passCompareString  is to to false in each test case when necessary.

2022-05-03 23:07 UTC, paulbartell approved these changes

2022-05-04 03:42 UTC, merged